name = "aokframes-image-extraction"
main = "scheduled-worker.js"
compatibility_date = "2024-04-04"
compatibility_flags = ["nodejs_compat"]

# Run the scheduled task daily at 2:00 AM UTC
[triggers]
crons = ["0 2 * * *"] 