name = "aokframesv3"
compatibility_date = "2024-04-04"
compatibility_flags = ["nodejs_compat"]

# For Cloudflare Pages Functions
pages_build_output_dir = ".svelte-kit/cloudflare"

# Environment variables for the worker
[vars]
MY_R2_BUCKET = "aokframes-website-assets"

# R2 bucket binding configuration with proper access - use newer naming convention
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "aokframes-website-assets"
preview_bucket_name = "aokframes-website-assets"

# Also maintain backward compatibility with old binding name
[[r2_buckets]]
binding = "ASSETSBUCKET" 
bucket_name = "aokframes-website-assets"
preview_bucket_name = "aokframes-website-assets"
