name = "aokframesv3"
main = ".svelte-kit/cloudflare/worker.js"
compatibility_date = "2024-04-04"

[vars]
MY_R2_BUCKET = "aokframes-website-assets"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "aokframes-website-assets"
preview_bucket_name = "aokframes-website-assets-preview"
