// Generated by scripts/generate-portfolio-dimensions.js for width 3000
// Do not edit this file manually!

export const dimensionsMapW3000 = {
  "Acros100_Mamiya6_08_09_24_8.webp": { width: 3000, height: 3000 },
  "Acros100_Mamiya6_08_10_24_12.webp": { width: 3000, height: 3000 },
  "Acrosii_Bessa_09_12_23_1.webp": { width: 3000, height: 1500 },
  "Cinestill800t_MamiyaSix_07_16_23_12.webp": { width: 3000, height: 2958 },
  "Ektar100_Mamiya6_09_12_23_1.webp": { width: 3000, height: 3000 },
  "Ektar100_Mamiya6_09_12_23_6.webp": { width: 3000, height: 3000 },
  "Ektar100_Mamiya6_09_15_24_11.webp": { width: 3000, height: 3000 },
  "Gold200_Mamiya6_07_13_24_9.webp": { width: 3000, height: 3000 },
  "Lomo800_Mamiya6_06_09_24_1.webp": { width: 3000, height: 3000 },
  "Lomo800_Mamiya6_06_09_24_8.webp": { width: 3000, height: 3000 },
  "Portra400_Mamiya6_09_12_23_10.webp": { width: 3000, height: 3000 },
  "Portra800_BessaR_07_13_24_14.webp": { width: 3000, height: 2000 },
  "Portra800_F100_09_14_24_6.webp": { width: 3000, height: 2000 },
  "Portra800_Mamiya6_05_03_24_9.webp": { width: 3000, height: 3000 },
  "Portra800_R4m_01_03_25_11.webp": { width: 3000, height: 2000 },
  "Provia_Mamiya6_09_12_23_1.webp": { width: 3000, height: 3000 },
  "Provia_Mamiya6_09_12_23_15.webp": { width: 3000, height: 3000 },
  "Trix400_2_BessaR_08_12_24_6.webp": { width: 3000, height: 2000 },
  "Trix400_2_Mamiya6_08_08_24_12.webp": { width: 3000, height: 3000 },
  "Trix400_BessaR_08_12_24_20.webp": { width: 3000, height: 2000 },
  "Trix400_BessaR_08_12_24_24.webp": { width: 3000, height: 2000 },
  "Trix400_BessaR_08_12_24_25.webp": { width: 3000, height: 2000 },
  "Trix400_BessaR_08_12_24_29.webp": { width: 3000, height: 2000 },
  "Trix400_F100_08_17_24_11.webp": { width: 3000, height: 2000 },
  "Trix400_Mamiya6_03_24_24_11.webp": { width: 3000, height: 3000 },
  "Trix400_Mamiya6_06_22_24_1.webp": { width: 3000, height: 3000 },
  "Trix400_Mamiya6_08_08_24_5.webp": { width: 3000, height: 3000 }
} as const;

export type PortfolioImageFilenameW3000 = keyof typeof dimensionsMapW3000;
