// Generated by vite-plugin-generate-dimensions.js
export const dimensionsMap = {
  "Acros100_Mamiya6_08_09_24_8.jpg": { width: 3302, height: 3302 },
  "Acros100_Mamiya6_08_10_24_12.jpg": { width: 3308, height: 3308 },
  "Acrosii_Bessa_09_12_23_1.jpg": { width: 4044, height: 2022 },
  "Cinestill800t_MamiyaSix_07_16_23_12.jpg": { width: 3162, height: 3118 },
  "Ektar100_Mamiya6_09_12_23_1.jpg": { width: 3305, height: 3305 },
  "Ektar100_Mamiya6_09_12_23_6.jpg": { width: 3169, height: 3169 },
  "Ektar100_Mamiya6_09_15_24_11.jpg": { width: 3547, height: 3547 },
  "Gold200_Mamiya6_07_13_24_9.jpg": { width: 3147, height: 3147 },
  "Lomo800_Mamiya6_06_09_24_1.jpg": { width: 3302, height: 3302 },
  "Lomo800_Mamiya6_06_09_24_8.jpg": { width: 3288, height: 3288 },
  "Portra400_Mamiya6_09_12_23_10.jpg": { width: 3301, height: 3301 },
  "Portra800_BessaR_07_13_24_14.jpg": { width: 3934, height: 2623 },
  "Portra800_F100_09_14_24_6.jpg": { width: 3182, height: 2121 },
  "Portra800_Mamiya6_05_03_24_9.jpg": { width: 2959, height: 2959 },
  "Portra800_R4m_01_03_25_11.jpg": { width: 3290, height: 2193 },
  "Provia_Mamiya6_09_12_23_1.jpg": { width: 4979, height: 4979 },
  "Provia_Mamiya6_09_12_23_15.jpg": { width: 4740, height: 4740 },
  "Trix400_2_BessaR_08_12_24_6.jpg": { width: 3960, height: 2640 },
  "Trix400_2_Mamiya6_08_08_24_12.jpg": { width: 3261, height: 3261 },
  "Trix400_BessaR_08_12_24_20.jpg": { width: 4070, height: 2713 },
  "Trix400_BessaR_08_12_24_24.jpg": { width: 4073, height: 2715 },
  "Trix400_BessaR_08_12_24_25.jpg": { width: 4077, height: 2718 },
  "Trix400_BessaR_08_12_24_29.jpg": { width: 3667, height: 2445 },
  "Trix400_F100_08_17_24_11.jpg": { width: 4016, height: 2677 },
  "Trix400_Mamiya6_03_24_24_11.jpg": { width: 3302, height: 3302 },
  "Trix400_Mamiya6_06_22_24_1.jpg": { width: 3268, height: 3268 },
  "Trix400_Mamiya6_08_08_24_5.jpg": { width: 3302, height: 3302 }
} as const;

export type PortfolioImageFilename = keyof typeof dimensionsMap;
